/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TableBuilderRouteImport } from './routes/table-builder'
import { Route as FormBuilderRouteImport } from './routes/form-builder'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestingIndexRouteImport } from './routes/testing/index'
import { Route as FormBuilderIndexRouteImport } from './routes/form-builder/index'

const TableBuilderRoute = TableBuilderRouteImport.update({
  id: '/table-builder',
  path: '/table-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const FormBuilderRoute = FormBuilderRouteImport.update({
  id: '/form-builder',
  path: '/form-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestingIndexRoute = TestingIndexRouteImport.update({
  id: '/testing/',
  path: '/testing/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormBuilderIndexRoute = FormBuilderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FormBuilderRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/form-builder': typeof FormBuilderRouteWithChildren
  '/table-builder': typeof TableBuilderRoute
  '/form-builder/': typeof FormBuilderIndexRoute
  '/testing': typeof TestingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/table-builder': typeof TableBuilderRoute
  '/form-builder': typeof FormBuilderIndexRoute
  '/testing': typeof TestingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/form-builder': typeof FormBuilderRouteWithChildren
  '/table-builder': typeof TableBuilderRoute
  '/form-builder/': typeof FormBuilderIndexRoute
  '/testing/': typeof TestingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/form-builder'
    | '/table-builder'
    | '/form-builder/'
    | '/testing'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/table-builder' | '/form-builder' | '/testing'
  id:
    | '__root__'
    | '/'
    | '/form-builder'
    | '/table-builder'
    | '/form-builder/'
    | '/testing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FormBuilderRoute: typeof FormBuilderRouteWithChildren
  TableBuilderRoute: typeof TableBuilderRoute
  TestingIndexRoute: typeof TestingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/table-builder': {
      id: '/table-builder'
      path: '/table-builder'
      fullPath: '/table-builder'
      preLoaderRoute: typeof TableBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form-builder': {
      id: '/form-builder'
      path: '/form-builder'
      fullPath: '/form-builder'
      preLoaderRoute: typeof FormBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testing/': {
      id: '/testing/'
      path: '/testing'
      fullPath: '/testing'
      preLoaderRoute: typeof TestingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form-builder/': {
      id: '/form-builder/'
      path: '/'
      fullPath: '/form-builder/'
      preLoaderRoute: typeof FormBuilderIndexRouteImport
      parentRoute: typeof FormBuilderRoute
    }
  }
}

interface FormBuilderRouteChildren {
  FormBuilderIndexRoute: typeof FormBuilderIndexRoute
}

const FormBuilderRouteChildren: FormBuilderRouteChildren = {
  FormBuilderIndexRoute: FormBuilderIndexRoute,
}

const FormBuilderRouteWithChildren = FormBuilderRoute._addFileChildren(
  FormBuilderRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FormBuilderRoute: FormBuilderRouteWithChildren,
  TableBuilderRoute: TableBuilderRoute,
  TestingIndexRoute: TestingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
