import type { FormElementOrList, FormStep } from "@/types/form-types";

type TemplateList = Record<
	string,
	{ template: FormElementOrList[] | FormStep[]; name: string }
>;

export const templates: TemplateList = {
	signup: {
		name: "Signup Form",
		template: [
			{
				id: "signup-heading",
				name: "heading",
				fieldType: "H1",
				static: true,
				content: "Sign Up",
			},
			{
				id: "signup-paragraph",
				name: "paragraph",
				fieldType: "FieldDescription",
				static: true,
				content: "You need an account to get started",
			},
			{
				id: "signup-name",
				name: "name",
				fieldType: "Input",
				type: "text",
				label: "Name",
				placeholder: "Enter your Name",
				required: true,
			},
			{
				id: "signup-email",
				name: "email",
				fieldType: "Input",
				type: "email",
				label: "Email",
				placeholder: "Enter your Email",
				required: true,
			},
			{
				id: "signup-password",
				name: "password",
				fieldType: "Password",
				type: "password",
				label: "Password",
				placeholder: "Password",
				required: true,
			},
			{
				id: "signup-password-confirm",
				name: "confirmPassword",
				fieldType: "Password",
				type: "password",
				label: "Confirm Password",
				placeholder: "Confirm Password",
				required: true,
			},
			{
				id: "signup-agree",
				name: "agree",
				fieldType: "Checkbox",
				label: "I agree to the terms and conditions",
				required: true,
			},
		],
	},
	login: {
		name: "Login Form",
		template: [
			{
				id: "login-heading",
				name: "login",
				fieldType: "H1",
				static: true,
				content: "Login",
			},
			{
				id: "sign-up-paragraph",
				name: "paragraph",
				fieldType: "FieldDescription",
				static: true,
				content: "Login to create an account",
			},
			{
				id: "login-email",
				name: "email",
				label: "Email",
				fieldType: "Input",
				type: "email",
				placeholder: "Enter your Email",
			},
			{
				id: "login-password",
				name: "password",
				fieldType: "Password",
				placeholder: "Password",
				label: "Password",
				type: "password",
				required: true,
			},
		],
	},
	feedbackForm: {
		name: "Feedback Form",
		template: [
			{
				id: "feedback-heading",
				name: "feedbackForm",
				fieldType: "H1",
				static: true,
				content: "Feedback Form",
			},
			{
				id: "feedback-paragraph",
				name: "paragraph",
				fieldType: "FieldDescription",
				static: true,
				content: "Please provide your feedback",
			},
			{
				id: "feedback-comment",
				name: "comment",
				fieldType: "Textarea",
				placeholder: "Share your feedback",
				label: "Feedback Comment",
				required: true,
			},
		],
	},
	waitlist: {
		name: "Waitlist",
		template: [
			{
				id: "waitlist-heading",
				name: "waitlist",
				fieldType: "H1",
				static: true,
				content: "Waitlist",
			},
			{
				id: "waitlist-paragraph",
				name: "paragraph",
				fieldType: "FieldDescription",
				static: true,
				content: "Join our waitlist to get early access",
			},
			{
				id: "waitlist-email",
				name: "email",
				label: "Your Email",
				fieldType: "Input",
				type: "email",
				placeholder: "Enter your Email",
				required: true,
			},
		],
	},
	contactUs: {
		name: "Contact Us",
		template: [
			{
				id: "contact-heading",
				name: "heading",
				fieldType: "H2",
				static: true,
				content: "Contact us",
			},
			{
				id: "contact-paragraph",
				name: "paragraph",
				fieldType: "FieldDescription",
				static: true,
				content: "Please fill the form below to contact us",
			},
			[
				{
					id: "contact-name",
					name: "name",
					fieldType: "Input",
					type: "text",
					label: "Name",
					required: true,
					placeholder: "Enter your name",
				},
				{
					id: "contact-email",
					name: "email",
					fieldType: "Input",
					type: "email",
					label: "Email",
					required: true,
					placeholder: "Enter your email",
				},
			],
			{
				id: "contact-message",
				name: "message",
				fieldType: "Textarea",
				label: "Message",
				placeholder: "Enter your message",
				required: true,
			},
			{
				id: "contact-agree",
				name: "agree",
				fieldType: "Checkbox",
				label: "I agree to the terms and conditions",
				required: true,
			},
		],
	},
	multiStepForm: {
		name: "Survey Form",
		template: [
			{
				id: "survey-step-1",
				stepFields: [
					{
						id: "survey-personal-heading",
						name: "heading2",
						fieldType: "H2",
						static: true,
						content: "Personal Details",
					},
					{
						id: "survey-personal-paragraph",
						name: "paragraph",
						fieldType: "FieldDescription",
						static: true,
						content: "Please provide your personal details",
					},
					{
						id: "survey-first-name",
						name: "name",
						fieldType: "Input",
						placeholder: "First name",
						label: "First name",
						required: true,
					},
					{
						id: "survey-last-name",
						name: "lastName",
						fieldType: "Input",
						placeholder: "Last name",
						label: "Last name",
						required: true,
					},
				],
			},
			{
				id: "survey-step-2",
				stepFields: [
					{
						name: "heading2",
						id: "survey-contact-heading",
						fieldType: "H2",
						static: true,
						content: "Contact Information",
					},
					{
						name: "paragraph",
						id: "survey-contact-paragraph",
						fieldType: "FieldDescription",
						static: true,
						content: "Please provide your contact information",
					},
					{
						name: "yourEmail",
						id: "survey-contact-email",
						fieldType: "Input",
						label: "Your Email",
						type: "email",
						required: true,
						placeholder: "Enter your email",
					},
					{
						name: "phoneNumber",
						id: "survey-contact-phone",
						fieldType: "Input",
						label: "Phone Number",
						type: "number",
						placeholder: "Enter your phone number",
						required: true,
					},
				],
			},
			{
				id: "survey-step-3",
				stepFields: [
					{
						name: "step2",
						id: "survey-preferences-heading",
						fieldType: "H2",
						static: true,
						content: "Your Preferences",
					},
					{
						id: "survey-preferences-toggle",
						name: "preferences",
						fieldType: "ToggleGroup",
						type: "multiple",
						label: "Tell us about your interests and preferences.",
						options: [
							{ label: "Technology", value: "technology" },
							{ label: "Business", value: "Business" },
							{ label: "Health", value: "Health" },
							{ label: "Science", value: "Science" },
						],
						required: true,
					},
					{
						id: "survey-preferences-comment",
						name: "comment",
						fieldType: "Textarea",
						placeholder: "Share your feedback",
						label: "Feedback Comment",
						required: true,
					},
				],
			},
		],
	},
	jobApplication: {
		name: "Job Application",
		template: [
			{
				id: "job-heading",
				name: "jobApplication",
				fieldType: "H1",
				static: true,
				content: "Job Application",
			},
			{
				id: "job-paragraph",
				name: "paragraph",
				fieldType: "FieldDescription",
				static: true,
				content: "Please fill out the form below to apply for this position",
			},
			[
				{
					id: "job-first-name",
					name: "firstName",
					fieldType: "Input",
					type: "text",
					label: "First Name",
					required: true,
					placeholder: "Enter your first name",
				},
				{
					id: "job-last-name",
					name: "lastName",
					fieldType: "Input",
					type: "text",
					label: "Last Name",
					required: true,
					placeholder: "Enter your last name",
				},
			],
			{
				id: "job-email",
				name: "email",
				fieldType: "Input",
				type: "email",
				label: "Email Address",
				required: true,
				placeholder: "Enter your email address",
			},
			{
				id: "github-url",
				name: "githubUrl",
				fieldType: "Input",
				type: "url",
				label: "GitHub URL",
				required: false,
				placeholder: "Enter your GitHub URL",
			},
			{
				id: "linkedin-url",
				name: "linkedinUrl",
				fieldType: "Input",
				type: "url",
				label: "LinkedIn URL",
				required: false,
				placeholder: "Enter your LinkedIn URL",
			},
			{
				id: "job-position",
				name: "position",
				fieldType: "RadioGroup",
				// placeholder: "Select Position",
				label: "Which position are you applying for?",
				required: true,
				options: [
					{ label: "Frontend Developer", value: "frontend" },
					{ label: "Backend Developer", value: "backend" },
					{ label: "Full Stack Developer", value: "fullstack" },
					{ label: "UI/UX Designer", value: "designer" },
					{ label: "Product Manager", value: "pm" },
				],
			},
			{
				id: "job-experience",
				name: "experience",
				fieldType: "Select",
				placeholder: "Select Experience",
				label: "Years of Experience",
				required: true,
				options: [
					{ label: "0-1 years", value: "0-1" },
					{ label: "2-3 years", value: "2-3" },
					{ label: "4-5 years", value: "4-5" },
					{ label: "6-10 years", value: "6-10" },
					{ label: "10+ years", value: "10+" },
				],
			},
			{
				id: "job-cover-letter",
				name: "coverLetter",
				fieldType: "Textarea",
				label: "Cover Letter",
				placeholder: "Tell us why you're interested in this position...",
			},
		],
	},
	eventRegistration: {
		name: "Event Registration",
		template: [
			{
				id: "event-heading",
				name: "eventRegistration",
				fieldType: "H1",
				static: true,
				content: "Event Registration",
			},
			{
				id: "event-paragraph",
				name: "paragraph",
				fieldType: "FieldDescription",
				static: true,
				content: "Register for our upcoming event",
			},
			[
				{
					id: "event-first-name",
					name: "firstName",
					fieldType: "Input",
					type: "text",
					label: "First Name",
					required: true,
					placeholder: "Enter your first name",
				},
				{
					id: "event-last-name",
					name: "lastName",
					fieldType: "Input",
					type: "text",
					label: "Last Name",
					required: true,
					placeholder: "Enter your last name",
				},
			],
			{
				id: "event-email",
				name: "email",
				fieldType: "Input",
				type: "email",
				label: "Email Address",
				required: true,
				placeholder: "Enter your email address",
			},
			{
				id: "event-company",
				name: "company",
				fieldType: "Input",
				type: "text",
				label: "Company/Organization",
				placeholder: "Enter your company name",
			},
			{
				id: "event-ticket-type",
				name: "ticketType",
				fieldType: "RadioGroup",
				label: "Ticket Type",
				required: true,
				options: [
					{ label: "General Admission - Free", value: "general" },
					{ label: "VIP Access - $99", value: "vip" },
					{ label: "Premium Package - $199", value: "premium" },
				],
			},
			{
				id: "event-comments",
				name: "comments",
				fieldType: "Textarea",
				label: "Additional Comments",
				placeholder: "Any special requirements or questions?",
			},
		],
	},
	productOrder: {
		name: "Product Order",
		template: [
			{
				id: "order-heading",
				name: "productOrder",
				fieldType: "H1",
				static: true,
				content: "Place Your Order",
			},
			{
				id: "order-paragraph",
				name: "paragraph",
				fieldType: "FieldDescription",
				static: true,
				content: "Fill out the details below to complete your order",
			},
			{
				id: "order-product",
				name: "product",
				fieldType: "Select",
				label: "Select Product",
				placeholder: "Select Product",
				required: true,
				options: [
					{ label: "Basic Plan - $29/month", value: "basic" },
					{ label: "Pro Plan - $59/month", value: "pro" },
					{ label: "Enterprise Plan - $99/month", value: "enterprise" },
				],
			},
			[
				{
					id: "order-first-name",
					name: "firstName",
					fieldType: "Input",
					type: "text",
					label: "First Name",
					required: true,
					placeholder: "Enter your first name",
				},
				{
					id: "order-last-name",
					name: "lastName",
					fieldType: "Input",
					type: "text",
					label: "Last Name",
					required: true,
					placeholder: "Enter your last name",
				},
			],
			{
				id: "order-email",
				name: "email",
				fieldType: "Input",
				type: "email",
				label: "Email Address",
				required: true,
				placeholder: "Enter your email address",
			},
			{
				id: "order-billing-address",
				name: "billingAddress",
				fieldType: "Textarea",
				label: "Billing Address",
				required: true,
				placeholder: "Enter your complete billing address",
			},
			{
				id: "order-payment-method",
				name: "paymentMethod",
				fieldType: "RadioGroup",
				label: "Payment Method",
				required: true,
				options: [
					{ label: "Credit Card", value: "credit" },
					{ label: "PayPal", value: "paypal" },
					{ label: "Bank Transfer", value: "bank" },
				],
			},
			{
				id: "order-terms",
				name: "terms",
				fieldType: "Checkbox",
				label: "I agree to the terms and conditions",
				required: true,
			},
		],
	},
	customerSupport: {
		name: "Customer Support",
		template: [
			{
				id: "support-heading",
				name: "customerSupport",
				fieldType: "H1",
				static: true,
				content: "Customer Support Request",
			},
			{
				id: "support-paragraph",
				name: "paragraph",
				fieldType: "FieldDescription",
				static: true,
				content: "We're here to help! Please describe your issue below.",
			},
			[
				{
					id: "support-first-name",
					name: "firstName",
					fieldType: "Input",
					type: "text",
					label: "First Name",
					required: true,
					placeholder: "Enter your first name",
				},
				{
					id: "support-last-name",
					name: "lastName",
					fieldType: "Input",
					type: "text",
					label: "Last Name",
					required: true,
					placeholder: "Enter your last name",
				},
			],
			{
				id: "support-email",
				name: "email",
				fieldType: "Input",
				type: "email",
				label: "Email Address",
				required: true,
				placeholder: "Enter your email address",
			},
			{
				id: "support-order-number",
				name: "orderNumber",
				fieldType: "Input",
				type: "text",
				label: "Order Number (if applicable)",
				placeholder: "Enter your order number",
			},
			{
				id: "support-category",
				name: "category",
				fieldType: "Select",
				placeholder: "Select Category",
				label: "Issue Category",
				required: true,
				options: [
					{ label: "Technical Issue", value: "technical" },
					{ label: "Billing Question", value: "billing" },
					{ label: "Product Inquiry", value: "product" },
					{ label: "Account Access", value: "account" },
					{ label: "Other", value: "other" },
				],
			},
			{
				id: "support-priority",
				name: "priority",
				fieldType: "RadioGroup",
				label: "Priority Level",
				required: true,
				options: [
					{ label: "Low - General inquiry", value: "low" },
					{ label: "Medium - Issue affecting usage", value: "medium" },
					{ label: "High - Urgent issue", value: "high" },
				],
			},
			{
				id: "support-description",
				name: "description",
				fieldType: "Textarea",
				label: "Issue Description",
				required: true,
				placeholder: "Please describe your issue in detail...",
			},
		],
	},
};
