/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestingRouteImport } from './routes/testing'
import { Route as TableBuilderRouteImport } from './routes/table-builder'
import { Route as FormRegistryRouteImport } from './routes/form-registry'
import { Route as FormBuilderRouteImport } from './routes/form-builder'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TableBuilderIndexRouteImport } from './routes/table-builder/index'
import { Route as FormBuilderIndexRouteImport } from './routes/form-builder/index'
import { Route as RIdDotjsonRouteImport } from './routes/r/$id[.]json'
import { Route as FormBuilderShareRouteImport } from './routes/form-builder/share'

const TestingRoute = TestingRouteImport.update({
  id: '/testing',
  path: '/testing',
  getParentRoute: () => rootRouteImport,
} as any)
const TableBuilderRoute = TableBuilderRouteImport.update({
  id: '/table-builder',
  path: '/table-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const FormRegistryRoute = FormRegistryRouteImport.update({
  id: '/form-registry',
  path: '/form-registry',
  getParentRoute: () => rootRouteImport,
} as any)
const FormBuilderRoute = FormBuilderRouteImport.update({
  id: '/form-builder',
  path: '/form-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TableBuilderIndexRoute = TableBuilderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TableBuilderRoute,
} as any)
const FormBuilderIndexRoute = FormBuilderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FormBuilderRoute,
} as any)
const RIdDotjsonRoute = RIdDotjsonRouteImport.update({
  id: '/r/$id.json',
  path: '/r/$id.json',
  getParentRoute: () => rootRouteImport,
} as any)
const FormBuilderShareRoute = FormBuilderShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => FormBuilderRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/form-builder': typeof FormBuilderRouteWithChildren
  '/form-registry': typeof FormRegistryRoute
  '/table-builder': typeof TableBuilderRouteWithChildren
  '/testing': typeof TestingRoute
  '/form-builder/share': typeof FormBuilderShareRoute
  '/r/$id.json': typeof RIdDotjsonRoute
  '/form-builder/': typeof FormBuilderIndexRoute
  '/table-builder/': typeof TableBuilderIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/form-registry': typeof FormRegistryRoute
  '/testing': typeof TestingRoute
  '/form-builder/share': typeof FormBuilderShareRoute
  '/r/$id.json': typeof RIdDotjsonRoute
  '/form-builder': typeof FormBuilderIndexRoute
  '/table-builder': typeof TableBuilderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/form-builder': typeof FormBuilderRouteWithChildren
  '/form-registry': typeof FormRegistryRoute
  '/table-builder': typeof TableBuilderRouteWithChildren
  '/testing': typeof TestingRoute
  '/form-builder/share': typeof FormBuilderShareRoute
  '/r/$id.json': typeof RIdDotjsonRoute
  '/form-builder/': typeof FormBuilderIndexRoute
  '/table-builder/': typeof TableBuilderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/form-builder'
    | '/form-registry'
    | '/table-builder'
    | '/testing'
    | '/form-builder/share'
    | '/r/$id.json'
    | '/form-builder/'
    | '/table-builder/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/form-registry'
    | '/testing'
    | '/form-builder/share'
    | '/r/$id.json'
    | '/form-builder'
    | '/table-builder'
  id:
    | '__root__'
    | '/'
    | '/form-builder'
    | '/form-registry'
    | '/table-builder'
    | '/testing'
    | '/form-builder/share'
    | '/r/$id.json'
    | '/form-builder/'
    | '/table-builder/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FormBuilderRoute: typeof FormBuilderRouteWithChildren
  FormRegistryRoute: typeof FormRegistryRoute
  TableBuilderRoute: typeof TableBuilderRouteWithChildren
  TestingRoute: typeof TestingRoute
  RIdDotjsonRoute: typeof RIdDotjsonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testing': {
      id: '/testing'
      path: '/testing'
      fullPath: '/testing'
      preLoaderRoute: typeof TestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table-builder': {
      id: '/table-builder'
      path: '/table-builder'
      fullPath: '/table-builder'
      preLoaderRoute: typeof TableBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form-registry': {
      id: '/form-registry'
      path: '/form-registry'
      fullPath: '/form-registry'
      preLoaderRoute: typeof FormRegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form-builder': {
      id: '/form-builder'
      path: '/form-builder'
      fullPath: '/form-builder'
      preLoaderRoute: typeof FormBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table-builder/': {
      id: '/table-builder/'
      path: '/'
      fullPath: '/table-builder/'
      preLoaderRoute: typeof TableBuilderIndexRouteImport
      parentRoute: typeof TableBuilderRoute
    }
    '/form-builder/': {
      id: '/form-builder/'
      path: '/'
      fullPath: '/form-builder/'
      preLoaderRoute: typeof FormBuilderIndexRouteImport
      parentRoute: typeof FormBuilderRoute
    }
    '/r/$id.json': {
      id: '/r/$id.json'
      path: '/r/$id.json'
      fullPath: '/r/$id.json'
      preLoaderRoute: typeof RIdDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form-builder/share': {
      id: '/form-builder/share'
      path: '/share'
      fullPath: '/form-builder/share'
      preLoaderRoute: typeof FormBuilderShareRouteImport
      parentRoute: typeof FormBuilderRoute
    }
  }
}

interface FormBuilderRouteChildren {
  FormBuilderShareRoute: typeof FormBuilderShareRoute
  FormBuilderIndexRoute: typeof FormBuilderIndexRoute
}

const FormBuilderRouteChildren: FormBuilderRouteChildren = {
  FormBuilderShareRoute: FormBuilderShareRoute,
  FormBuilderIndexRoute: FormBuilderIndexRoute,
}

const FormBuilderRouteWithChildren = FormBuilderRoute._addFileChildren(
  FormBuilderRouteChildren,
)

interface TableBuilderRouteChildren {
  TableBuilderIndexRoute: typeof TableBuilderIndexRoute
}

const TableBuilderRouteChildren: TableBuilderRouteChildren = {
  TableBuilderIndexRoute: TableBuilderIndexRoute,
}

const TableBuilderRouteWithChildren = TableBuilderRoute._addFileChildren(
  TableBuilderRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FormBuilderRoute: FormBuilderRouteWithChildren,
  FormRegistryRoute: FormRegistryRoute,
  TableBuilderRoute: TableBuilderRouteWithChildren,
  TestingRoute: TestingRoute,
  RIdDotjsonRoute: RIdDotjsonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
