/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestingRouteImport } from './routes/testing'
import { Route as FormBuilderRouteImport } from './routes/form-builder'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FormBuilderIndexRouteImport } from './routes/form-builder/index'
import { Route as OrpcDemoTableRouteImport } from './routes/orpc/demo.table'
import { Route as OrpcDemoOrpcTodoRouteImport } from './routes/orpc/demo.orpc-todo'
import { ServerRoute as OrpcApiSplatServerRouteImport } from './routes/orpc/api.$'
import { ServerRoute as OrpcApiRpcSplatServerRouteImport } from './routes/orpc/api.rpc.$'

const rootServerRouteImport = createServerRootRoute()

const TestingRoute = TestingRouteImport.update({
  id: '/testing',
  path: '/testing',
  getParentRoute: () => rootRouteImport,
} as any)
const FormBuilderRoute = FormBuilderRouteImport.update({
  id: '/form-builder',
  path: '/form-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormBuilderIndexRoute = FormBuilderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FormBuilderRoute,
} as any)
const OrpcDemoTableRoute = OrpcDemoTableRouteImport.update({
  id: '/orpc/demo/table',
  path: '/orpc/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const OrpcDemoOrpcTodoRoute = OrpcDemoOrpcTodoRouteImport.update({
  id: '/orpc/demo/orpc-todo',
  path: '/orpc/demo/orpc-todo',
  getParentRoute: () => rootRouteImport,
} as any)
const OrpcApiSplatServerRoute = OrpcApiSplatServerRouteImport.update({
  id: '/orpc/api/$',
  path: '/orpc/api/$',
  getParentRoute: () => rootServerRouteImport,
} as any)
const OrpcApiRpcSplatServerRoute = OrpcApiRpcSplatServerRouteImport.update({
  id: '/orpc/api/rpc/$',
  path: '/orpc/api/rpc/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/form-builder': typeof FormBuilderRouteWithChildren
  '/testing': typeof TestingRoute
  '/form-builder/': typeof FormBuilderIndexRoute
  '/orpc/demo/orpc-todo': typeof OrpcDemoOrpcTodoRoute
  '/orpc/demo/table': typeof OrpcDemoTableRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/testing': typeof TestingRoute
  '/form-builder': typeof FormBuilderIndexRoute
  '/orpc/demo/orpc-todo': typeof OrpcDemoOrpcTodoRoute
  '/orpc/demo/table': typeof OrpcDemoTableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/form-builder': typeof FormBuilderRouteWithChildren
  '/testing': typeof TestingRoute
  '/form-builder/': typeof FormBuilderIndexRoute
  '/orpc/demo/orpc-todo': typeof OrpcDemoOrpcTodoRoute
  '/orpc/demo/table': typeof OrpcDemoTableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/form-builder'
    | '/testing'
    | '/form-builder/'
    | '/orpc/demo/orpc-todo'
    | '/orpc/demo/table'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/testing'
    | '/form-builder'
    | '/orpc/demo/orpc-todo'
    | '/orpc/demo/table'
  id:
    | '__root__'
    | '/'
    | '/form-builder'
    | '/testing'
    | '/form-builder/'
    | '/orpc/demo/orpc-todo'
    | '/orpc/demo/table'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FormBuilderRoute: typeof FormBuilderRouteWithChildren
  TestingRoute: typeof TestingRoute
  OrpcDemoOrpcTodoRoute: typeof OrpcDemoOrpcTodoRoute
  OrpcDemoTableRoute: typeof OrpcDemoTableRoute
}
export interface FileServerRoutesByFullPath {
  '/orpc/api/$': typeof OrpcApiSplatServerRoute
  '/orpc/api/rpc/$': typeof OrpcApiRpcSplatServerRoute
}
export interface FileServerRoutesByTo {
  '/orpc/api/$': typeof OrpcApiSplatServerRoute
  '/orpc/api/rpc/$': typeof OrpcApiRpcSplatServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/orpc/api/$': typeof OrpcApiSplatServerRoute
  '/orpc/api/rpc/$': typeof OrpcApiRpcSplatServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/orpc/api/$' | '/orpc/api/rpc/$'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/orpc/api/$' | '/orpc/api/rpc/$'
  id: '__root__' | '/orpc/api/$' | '/orpc/api/rpc/$'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  OrpcApiSplatServerRoute: typeof OrpcApiSplatServerRoute
  OrpcApiRpcSplatServerRoute: typeof OrpcApiRpcSplatServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testing': {
      id: '/testing'
      path: '/testing'
      fullPath: '/testing'
      preLoaderRoute: typeof TestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form-builder': {
      id: '/form-builder'
      path: '/form-builder'
      fullPath: '/form-builder'
      preLoaderRoute: typeof FormBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form-builder/': {
      id: '/form-builder/'
      path: '/'
      fullPath: '/form-builder/'
      preLoaderRoute: typeof FormBuilderIndexRouteImport
      parentRoute: typeof FormBuilderRoute
    }
    '/orpc/demo/table': {
      id: '/orpc/demo/table'
      path: '/orpc/demo/table'
      fullPath: '/orpc/demo/table'
      preLoaderRoute: typeof OrpcDemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orpc/demo/orpc-todo': {
      id: '/orpc/demo/orpc-todo'
      path: '/orpc/demo/orpc-todo'
      fullPath: '/orpc/demo/orpc-todo'
      preLoaderRoute: typeof OrpcDemoOrpcTodoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/orpc/api/$': {
      id: '/orpc/api/$'
      path: '/orpc/api/$'
      fullPath: '/orpc/api/$'
      preLoaderRoute: typeof OrpcApiSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/orpc/api/rpc/$': {
      id: '/orpc/api/rpc/$'
      path: '/orpc/api/rpc/$'
      fullPath: '/orpc/api/rpc/$'
      preLoaderRoute: typeof OrpcApiRpcSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface FormBuilderRouteChildren {
  FormBuilderIndexRoute: typeof FormBuilderIndexRoute
}

const FormBuilderRouteChildren: FormBuilderRouteChildren = {
  FormBuilderIndexRoute: FormBuilderIndexRoute,
}

const FormBuilderRouteWithChildren = FormBuilderRoute._addFileChildren(
  FormBuilderRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FormBuilderRoute: FormBuilderRouteWithChildren,
  TestingRoute: TestingRoute,
  OrpcDemoOrpcTodoRoute: OrpcDemoOrpcTodoRoute,
  OrpcDemoTableRoute: OrpcDemoTableRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  OrpcApiSplatServerRoute: OrpcApiSplatServerRoute,
  OrpcApiRpcSplatServerRoute: OrpcApiRpcSplatServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
